"""
Smoke test that `alembic upgrade head` (migrations.run_migrations, called
from main.py's lifespan on every startup) actually produces the schema
models.py declares -- autogenerated migrations are easy to get right once
and then silently drift from the models over time.
"""
from sqlalchemy import create_engine, inspect

from frontend_fastapi.migrations import run_migrations


def test_migrations_produce_the_expected_tables(tmp_path):
    db_path = tmp_path / "migration_smoke_test.sqlite3"
    database_url = f"sqlite:///{db_path}"

    run_migrations(database_url)

    engine = create_engine(database_url)
    tables = set(inspect(engine).get_table_names())
    engine.dispose()

    assert {"users", "sessions", "project_documents"} <= tables
    assert db_path.exists()


def test_users_department_column_matches_the_form_validator_length(tmp_path):
    """Regression test: forms/accounts.py's _IdentityForm.department field
    allows up to 200 characters (matching Django's Profile.department) --
    the column itself must actually accommodate that, not silently
    truncate (SQLite) or raise an unhandled DB error (Postgres) for a
    151-200 character submission that passed form validation."""
    db_path = tmp_path / "migration_column_test.sqlite3"
    database_url = f"sqlite:///{db_path}"
    run_migrations(database_url)

    engine = create_engine(database_url)
    columns = {c["name"]: c for c in inspect(engine).get_columns("users")}
    engine.dispose()

    assert columns["department"]["type"].length == 200
