"""
Smoke test that `alembic upgrade head` (migrations.run_migrations, called
from main.py's lifespan on every startup) actually produces the schema
models.py declares -- autogenerated migrations are easy to get right once
and then silently drift from the models over time.
"""
from sqlalchemy import create_engine, inspect

from frontend_fastapi.migrations import run_migrations


def test_migrations_produce_the_expected_tables(tmp_path):
    db_path = tmp_path / "migration_smoke_test.sqlite3"
    database_url = f"sqlite:///{db_path}"

    run_migrations(database_url)

    engine = create_engine(database_url)
    tables = set(inspect(engine).get_table_names())
    engine.dispose()

    assert {"users", "sessions", "project_documents"} <= tables
    assert db_path.exists()
