"""
SQLAlchemy engine/session for this project's OWN local database (users,
sessions, project_documents) -- see settings.DATABASE_URL and models.py's
module docstring for why this is never the same database as HermesDB or the
anon-mapping DB.
"""
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

from frontend_fastapi.settings import DATABASE_URL

# check_same_thread=False: FastAPI runs sync path-operation functions (and
# sync dependencies) in a worker thread, not always the thread that created
# the engine -- sqlite's default same-thread check would otherwise reject
# those connections. Not needed (and not passed) for Postgres.
_connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(DATABASE_URL, connect_args=_connect_args)
SessionLocal = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)


def get_db() -> Session:
    """
    Request-scoped DB session. Commits once, automatically, if the request
    completes without raising -- so an ordinary route (flash a message, log
    a user in, save an upload) doesn't need its own explicit db.commit()
    call, and a mid-request exception can't leave a half-applied write
    behind. Route handlers that need an object's autogenerated state
    reflected mid-request (rare -- our primary keys are client-generated,
    see models.py) can still call db.flush() themselves.
    """
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
